# Generated by Django 4.2.20 on 2025-04-11 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('min_points', models.IntegerField(verbose_name='Pontos Mínimos')),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Desconto (%)')),
                ('points_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=3, verbose_name='Multiplicador de Pontos')),
            ],
            options={
                'verbose_name': 'Nível de Fidelidade',
                'verbose_name_plural': 'Níveis de Fidelidade',
                'ordering': ['min_points'],
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AddField(
            model_name='customer',
            name='loyalty_points',
            field=models.IntegerField(default=0, verbose_name='Pontos de Fidelidade'),
        ),
        migrations.CreateModel(
            name='LoyaltyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(verbose_name='Pontos')),
                ('transaction_type', models.CharField(choices=[('EARN', 'Ganhou Pontos'), ('REDEEM', 'Resgatou Pontos'), ('EXPIRE', 'Pontos Expirados'), ('BONUS', 'Pontos Bônus')], max_length=10, verbose_name='Tipo')),
                ('description', models.CharField(max_length=200, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_transactions', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Transação de Pontos',
                'verbose_name_plural': 'Transações de Pontos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='loyalty_tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.loyaltytier', verbose_name='Nível de Fidelidade'),
        ),
    ]
