# Generated by Django 4.2.20 on 2025-04-13 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_company_created_at_company_is_active_company_owner_and_more'),
        ('customers', '0003_customer_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='core.company', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='loyaltytier',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_tiers', to='core.company', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='loyaltytier',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='loyaltytier',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('company', 'email'), ('company', 'phone')},
        ),
        migrations.AlterUniqueTogether(
            name='loyaltytier',
            unique_together={('company', 'name')},
        ),
        migrations.RemoveField(
            model_name='loyaltytier',
            name='points_multiplier',
        ),
    ]
