# Generated by Django 4.2.20 on 2025-04-13 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_company_created_at_company_is_active_company_owner_and_more'),
        ('customers', '0005_associate_company_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='core.company', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='loyaltytier',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_tiers', to='core.company', verbose_name='Empresa'),
        ),
    ]
