"""
Django settings for saas_crm project.

Generated by 'django-admin startproject' using Django 4.2.20.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-5y&gx0t64hsi9ysc8f)g%!vs&wp5ytl%-+6wi*tfkff^*x7l06'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',  # Tema para o Django Admin
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    
    # Aplicativos de terceiros
    'crispy_forms',
    'crispy_bootstrap5',
    
    # Aplicativos locais
    'core',
    'products',
    'sales',
    'customers',
    'dashboard',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'core.middleware.AuthenticationExemptMiddleware',  # Middleware para isenção de login (deve vir antes do auth middleware)
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.CompanyMiddleware',  # Middleware da empresa
]

ROOT_URLCONF = 'saas_crm.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'saas_crm.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Crispy Forms
CRISPY_ALLOWED_TEMPLATE_PACKS = 'bootstrap5'
CRISPY_TEMPLATE_PACK = 'bootstrap5'

# Login URLs
LOGIN_REDIRECT_URL = 'dashboard:dashboard'
LOGIN_URL = 'login'
LOGIN_EXEMPT_URLS = ['vendas/recibo/', 'vendas/r/']  # URLs que não exigem login

# Configurações de CSRF
CSRF_COOKIE_HTTPONLY = False  # Permite que JavaScript acesse o cookie CSRF
CSRF_COOKIE_SECURE = False    # True em produção com HTTPS
CSRF_COOKIE_SAMESITE = 'Lax'  # Relaxa a política SameSite
CSRF_TRUSTED_ORIGINS = ['http://localhost:8000', 'http://127.0.0.1:8000']  # Origens confiáveis
SESSION_COOKIE_SECURE = False # True em produção com HTTPS
SESSION_COOKIE_SAMESITE = 'Lax'  # Relaxa a política SameSite

# Configurações do Jazzmin (tema do Admin)
JAZZMIN_SETTINGS = {
    # título mostrado na aba do navegador
    "site_title": "SnapDev CRM Admin",
    
    # Título no cabeçalho do admin
    "site_header": "SnapDev CRM",
    
    # Título na página inicial do admin
    "site_brand": "SnapDev CRM",
    
    # Link da logo no cabeçalho
    "site_logo": None,
    
    # CSS classes para o site brand
    "site_logo_classes": "fas fa-store",
    
    # Link de boas-vindas no topo do menu
    "welcome_sign": "Administração do SaaS",
    
    # Ícone de copyright (ex: "fas fa-copyright")
    "copyright": "SnapDev CRM",
    
    # Lista de apps a serem mostrados no menu (com ordem específica)
    "order_with_respect_to": ["auth", "core"],
    
    # Links personalizados para mostrar na barra lateral
    "custom_links": {
        "admin": [{
            # Django Admin
            "name": "Dashboard SaaS",
            "url": "admin:saas_dashboard",
            "icon": "fas fa-tachometer-alt",
        }],
    },
    
    # Ícones para as aplicações/models no menu (usando FontAwesome)
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "core.company": "fas fa-building",
        "core.subscription": "fas fa-credit-card",
    },
    
    # Apps que não serão exibidas no menu do admin
    "hide_apps": ["dashboard", "products", "sales", "customers"],
    
    # Models que não serão exibidas no menu do admin
    "hide_models": ["products.product", "products.category", "dashboard.expense", "dashboard.expensecategory", "sales.sale", "customers.customer"],
    
    # Mostra interface do usuário para escolher permissões
    "show_ui_builder": False,
    
    # Links relacionados, pra cada model
    "related_modal_active": True,
}

# Interface customizada para o usuário
JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-primary",
    "accent": "accent-primary",
    "navbar": "navbar-primary navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "default",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}

# Planos de assinatura com preços
SUBSCRIPTION_PLANS = {
    'basic': {
        'name': 'Básico',
        'price': 0,
        'features': [
            'Até 7 produtos',
            'Gerenciamento de vendas',
            'Relatórios básicos',
        ],
    },
    'standard': {
        'name': 'Padrão',
        'price': 29.90,
        'features': [
            'Até 30 produtos',
            'Gerenciamento de vendas completo',
            'Relatórios avançados',
            'Controle de estoque',
            'Suporte por e-mail',
        ],
    },
    'premium': {
        'name': 'Premium',
        'price': 49.00,
        'features': [
            'Produtos ilimitados',
            'Todas as funcionalidades do plano Padrão',
            'Painel de controle avançado',
            'Suporte prioritário',
            'Backup diário',
            'Personalização de relatórios',
        ],
    },
}
