# Generated by Django 4.2.20 on 2025-04-13 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_paymentmethod_company_sale_company_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='paymentmethod',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='company',
        ),
    ]
