# Generated by Django 4.2.20 on 2025-04-13 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_company_created_at_company_is_active_company_owner_and_more'),
        ('sales', '0004_add_company_to_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='core.company', verbose_name='Empresa'),
        ),
        migrations.AlterUniqueTogether(
            name='paymentmethod',
            unique_together={('company', 'name')},
        ),
    ]
