# Generated by Django 4.2.20 on 2025-04-13 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_company_created_at_company_is_active_company_owner_and_more'),
        ('sales', '0005_paymentmethod_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='core.company', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='core.company', verbose_name='Empresa'),
        ),
    ]
