# Generated by Django 4.2.20 on 2025-04-13 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_alter_paymentmethod_company_alter_sale_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Custo'),
        ),
    ]
