# Generated by Django 4.2.20 on 2025-04-15 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_add_financial_metrics'),
        ('sales', '0008_sale_access_token_sale_canceled_at_sale_canceled_by_and_more'),
    ]

    operations = [
    ]
