# Generated by Django 4.2.20 on 2025-04-17 02:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_alter_customer_company_alter_loyaltytier_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0005_color_product_has_variations_alter_category_name_and_more'),
        ('sales', '0009_merge_20250415_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='sales.paymentmethod', verbose_name='Método de Pagamento'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Custo'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='products.product', verbose_name='Produto'),
        ),
    ]
