# Generated by Django 4.2.20 on 2025-04-13 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_company_created_at_company_is_active_company_owner_and_more'),
        ('products', '0003_category_company_product_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='core.company', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='product',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.company', verbose_name='Empresa'),
        ),
    ]
