# Generated by Django 4.2.20 on 2025-04-13 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_create_companies_for_users'),
        ('products', '0004_alter_category_company_alter_product_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('code', models.CharField(blank=True, help_text='Ex: #FF0000', max_length=7, null=True, verbose_name='Código Hex')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='core.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Cor',
                'verbose_name_plural': 'Cores',
                'ordering': ['name'],
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='has_variations',
            field=models.BooleanField(default=False, verbose_name='Possui variações'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Nome')),
                ('tipo', models.CharField(choices=[('roupa', 'Roupa'), ('calcado', 'Calçado')], default='roupa', max_length=10, verbose_name='Tipo')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem de exibição')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='core.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Tamanho',
                'verbose_name_plural': 'Tamanhos',
                'ordering': ['ordem', 'name'],
                'unique_together': {('company', 'name', 'tipo')},
            },
        ),
        migrations.CreateModel(
            name='ProductVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='Quantidade em estoque')),
                ('stock_alert_level', models.PositiveIntegerField(default=3, verbose_name='Nível de alerta de estoque')),
                ('sku', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='SKU')),
                ('price_adjustment', models.DecimalField(decimal_places=2, default=0, help_text='Valor a ser adicionado/subtraído do preço base do produto', max_digits=10, verbose_name='Ajuste de preço')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.color', verbose_name='Cor')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='products.product', verbose_name='Produto')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.size', verbose_name='Tamanho')),
            ],
            options={
                'verbose_name': 'Variação de Produto',
                'verbose_name_plural': 'Variações de Produtos',
                'unique_together': {('product', 'size', 'color')},
            },
        ),
    ]
